name: unidate
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.6
  flutter_svg:
  json_annotation: ^4.5.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  flutter_native_splash: ^2.3.4
  appinio_swiper: ^1.0.3
  google_fonts: ^6.1.0
  
  lazy_load_indexed_stack: ^1.0.1
  dotted_border: ^2.0.0+3
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.3.3
  get_storage: ^2.1.1
  file_picker: ^6.0.0
  cached_network_image: ^3.3.0
  mime: ^1.0.4
  http_parser: ^4.0.2
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  intl: ^0.18.1
  geolocator: ^10.1.0
  age_calculator: ^1.0.0
  smooth_page_indicator: ^1.1.0
  pull_to_refresh: ^2.0.0
  chatview: ^1.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.1
  icons_launcher: ^2.1.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/users/
    - assets/images/auth/
    - assets/images/setup/
    - assets/icons/
    - assets/icons/navigation_bar/

flutter_gen:
  output: lib/generated/
  line_length: 80
  
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: false

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/native_splash.png"
  android12: true
  android: true
  web: true
  ios: true
  remove_alpha_ios: true

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true